name = "bilibili-video-info-worker"
main = "src/index.js"
compatibility_date = "2025-05-14"
compatibility_flags = ["nodejs_compat"]

[[vars]]
ORIGIN = "https://api.bilibili.com"

[env.production]
name = "bilibili-video-info-worker-production"